baseURL = "https://www.chriswiegman.com/"
languageCode = "en-us"
title = "Chris Wiegman"
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    url = "mailto:contact@chriswiegman.com"

