baseURL = "https://chriswiegman.com/"
languageCode = "en-us"
title = "Chris Wiegman"
PygmentsCodeFences = true
PygmentsStyle = "trac"
pygmentsOptions = "linenos=table"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
enableGitInfo = true
disableHugoGeneratorInject = true
enableRobotsTXT = true

[params]
  mainSections = ["posts"]
  description = "Chris Wiegman is a software engineer working to make the lives of WordPress developers easier."
  images = ["/images/chris-wiegman-speaking.jpg"]
  subtitle = "Engineer, Teacher, Speaker, Writer"

[permalinks]
  posts = "/:year/:month/:title/"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 100
  [[menu.main]]
    name = "Speaking"
    url = "/speaking/"
    weight = 110
  [[menu.main]]
    name = "Contact"
    url = "mailto:contact@chriswiegman.com"
    weight = 120
