baseURL = "https://www.chriswiegman.com/"
languageCode = "en-us"
title = "Chris Wiegman"
PygmentsCodeFences = true
PygmentsStyle = "trac"
pygmentsOptions = "linenos=table"

[params]
  mainSections = ["posts"]

[permalinks]
  posts = "/:year/:month/:title/"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 100
  [[menu.main]]
    name = "Speaking"
    url = "/speaking/"
    weight = 110
  [[menu.main]]
    name = "Contact"
    url = "mailto:contact@chriswiegman.com"
    weight = 120

