[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.62.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

/css/*
  Cache-Control: public, max-age=360000
/images/*
  Cache-Control: public, max-age=360000
