[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.62.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
for = "/css/*"
[headers.values]
Cache-Control = "public, max-age=360000"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=360000"
