#!/bin/bash

# Uses Hugo to create a new post based on the current date and the provided title
# e.g., new my-awesome-blog-post will create content/YYYY/MM/my-awesome-blog-post/index.md

# Require one argument
if [ $# -eq 0 ]
  then
    echo "Usage: new <title-of-post>"
    exit
fi

yearPrefix=$(date +'%Y')
monthPrefix=$(date +'%Y-%m')
monthName=$(date +'%B')
postTitle=$1
pathSuffix="/index.md"

postPath="posts/$postTitle.md"

hugo new $postPath

if [ ! -f ./content/archy/$yearPrefix.md ]; then
  echo '---' >> ./content/archy/$yearPrefix.md;
  echo "title: \"Archive for $yearPrefix\"" >> ./content/archy/$yearPrefix.md;
  echo "date: \"$yearPrefix-01-01 00:00:00\"" >> ./content/archy/$yearPrefix.md;
  echo '---' >> ./content/archy/$yearPrefix.md;
fi

if [ ! -f ./content/archm/$monthPrefix.md ]; then
  echo '---' >> ./content/archm/$monthPrefix.md;
  echo "title: \"Archive for $monthName, $yearPrefix\"" >> ./content/archm/$monthPrefix.md;
  echo "date: \"$monthPrefix-01 00:00:00\"" >> ./content/archm/$monthPrefix.md;
  echo '---' >> ./content/archm/$monthPrefix.md;
fi
