#!/bin/bash

# Uses Hugo to create a new post based on the current date and the provided title
# e.g., new my-awesome-blog-post will create content/YYYY/MM/my-awesome-blog-post/index.md

# Require one argument
if [ $# -eq 0 ]
  then
    echo "Usage: new <title-of-post>"
    exit
fi

datePrefix=$(date +'%Y/%m/')
postTitle=$1
pathSuffix="/index.md"

postPath="posts/$datePrefix$postTitle$pathSuffix"

hugo new $postPath
